# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-30 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=32)),
                ('direccion', models.CharField(blank=True, max_length=32)),
                ('telefonos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=32)),
                ('descripcion', models.TextField(blank=True, max_length=232)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('puntos', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=232)),
            ],
            options={
                'verbose_name_plural': 'cliente tipo',
            },
        ),
        migrations.CreateModel(
            name='FormaContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, max_length=232, null=True)),
            ],
            options={
                'verbose_name_plural': 'Forma contacto',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='clienteTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.ClienteTipo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='formaContacto',
            field=models.ManyToManyField(to='Ventas.FormaContacto', verbose_name='formaContacto'),
        ),
    ]
