# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-02 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Pais',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Region',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=52),
        ),
    ]
