# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-30 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=43)),
                ('descripcion', models.TextField(max_length=232)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'InsumoCategoria',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=43)),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='insumoCategoria',
            field=models.ManyToManyField(to='Inventarios.InsumoCategoria', verbose_name='InsumoCategoria'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventarios.Medida'),
        ),
    ]
