# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-30 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=43)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio')),
                ('descripcion', models.TextField(blank=True, max_length=232, null=True)),
                ('cantidadAlmacen', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidadAlmacen')),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventarios.Insumo')),
                ('insumoCategoria', models.ManyToManyField(default=1, to='Inventarios.InsumoCategoria', verbose_name='InsumoCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('nitoCedula', models.CharField(blank=True, max_length=22)),
                ('nombre', models.CharField(max_length=32)),
                ('direccion', models.CharField(blank=True, max_length=32)),
                ('telefonos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=32)),
                ('descripcion', models.TextField(blank=True, max_length=232)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorContacto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('cargo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=32)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('banco', models.CharField(max_length=43)),
                ('tipo', models.CharField(choices=[('ahorro', 'AHORRO'), ('corriente', 'CORRIENTE')], max_length=10)),
                ('cuenta', models.BigIntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='insumoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.Proveedor'),
        ),
    ]
