# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-02 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoproveedor',
            name='insumoCategoria',
            field=models.ManyToManyField(to='Inventarios.InsumoCategoria', verbose_name='InsumoCategoria'),
        ),
    ]
